### ISSUE TITLE
AWS IOT access via SSL (not a problem with app)

### ISSUE THREAD

**Issue by fixingthingsguy** [Vetru-Apps/mqtt-dashboard-documentation#9]
Dear Developer, First off, great documentation with your app! And I followed them for AWS access as documented in your excellent tutorial under help. My problem is not your application, and if you can help direct me I would appreciate it
I have certs that work consistently on an esp8266/nodemcu.  I use those certs to access AWS and works very well all the time.
So I have tried to convert those certs using your openssl suggestion to create a pkcs12 format. Works fine, hit return when asked for password.
Now at the Android phone, it won't accept the above cert as a credential, maybe Android is very strict
And at the APP, directly providing the path for the CA and .p12 and blank for the password, results in the following messaage
![image](https://user-images.githubusercontent.com/7385839/146455968-34bb6d42-f925-470c-964c-1070c520c719.png)

**Comment by RoustamManookian** [comment]
Hi,
I have the same issue.
Did you succeed in connecting to AWS?

**Comment by fixingthingsguy** [comment]
Yes, if I remember right, on Android, you need to compile with keystore and include keystore info in your code naturally.
